CREATE TABLE FILE_NAMES
(
filename VARCHAR2(255)
);



CREATE TABLE DIM_CUSTOMERS
(
ID NUMBER,
ID_NK NUMBER,
NAME VARCHAR2(255), 
USERNAME VARCHAR2(255),
EMAIL VARCHAR2(150 BYTE),
DATEOFBIRTH DATE,
STREETADDRESS VARCHAR2(100 BYTE),
CITY VARCHAR2(150 BYTE),
COUNTRY VARCHAR2(150 BYTE),
ZIP VARCHAR2(50 BYTE),
STATE VARCHAR2(50 BYTE),
PHONE VARCHAR2(50 BYTE)
);


CREATE TABLE DIM_PRODUCTS
(
PROD_ID NUMBER,
PRODUCTS NUMBER, --NK
PRODUCTNAME VARCHAR2(255 BYTE),
COMPANYNAME VARCHAR2(255 BYTE),
PRICE VARCHAR2(255 BYTE),
WAREHOUSELOCATIONSTATE VARCHAR2(255 BYTE)
);

DROP SEQUENCE customers_seq;

CREATE SEQUENCE customers_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE TABLE CLS_CUSTOMERS
(
CUST_SURR_ID NUMBER,
ID NUMBER, 
NAME VARCHAR2(255), 
USERNAME VARCHAR2(255),
EMAIL VARCHAR2(150 BYTE),
DATEOFBIRTH DATE,
STREETADDRESS VARCHAR2(100 BYTE),
CITY VARCHAR2(150 BYTE),
COUNTRY VARCHAR2(150 BYTE),
ZIP VARCHAR2(50 BYTE),
STATE VARCHAR2(50 BYTE),
PHONE VARCHAR2(50 BYTE)
);

CREATE TABLE CLS_PRODUCTS
(
PROD_SURR_ID NUMBER,
PRODUCTS NUMBER,
PRODUCTNAME VARCHAR2(255 BYTE),
COMPANYNAME VARCHAR2(255 BYTE),
PRICE VARCHAR2(255 BYTE),
WAREHOUSELOCATIONSTATE VARCHAR2(255 BYTE)
);


DROP SEQUENCE products_seq;

CREATE SEQUENCE products_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE TABLE DIM_CREDIT_CARDS
(
CREDIT_CARD_ID NUMBER,
CreditCard VARCHAR2(255),
CreditCardNumber VARCHAR2(255)
);


CREATE TABLE CLS_CREDIT_CARDS
(
CREDIT_CARD_ID NUMBER,
CreditCard VARCHAR2(255),
CreditCardNumber VARCHAR2(255)
);


CREATE SEQUENCE cards_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE TABLE WRK_CREDIT_CARDS
(
CREDITCARD VARCHAR2(150),
CREDITCARDNUMBER VARCHAR2(150)
);


CREATE TABLE FCT_PURCHASES
(
PAYMENT_ID NUMBER ,
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER,
TRANSACTIONDATE DATE,
CREDIT_CARD_ID NUMBER,
isinterstate    NUMBER(2),
constraint pk_rr primary key(PAYMENT_ID,CUSTOMER_ID,PRODUCT_ID,CREDIT_CARD_ID )
);





